# affine function

In [2]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

In [24]:
for iii in range(3):
    
    x = tf.constant([[10.,20.]]) # input -> matrix
    print(f'x :{x}')
    dense=Dense(units=1, activation='linear') # affine function, linear 디폴트, linear일때 activation없이 그대로 나옴
    print(f'init :{dense.get_weights()}')
    y_tf = dense(x) # forward propagation + params initialization , 초기화 여기서
    

    W,B = dense.get_weights()
    print(f'W: {W}, B: {B}') # 초기 W는 랜덤
    
    print(f'y_tf :{y_tf}')
    y_man = tf.linalg.matmul(x,W)+B
    print(f'y_man :{y_man}')
    
    
    print(f'===== {iii} =====')
    
    

x :[[10. 20.]]
init :[]
W: [[ 0.8066164]
 [-1.0093138]], B: [0.]
y_tf :[[-12.120111]]
y_man :[[-12.120111]]
===== 0 =====
x :[[10. 20.]]
init :[]
W: [[-1.3778957]
 [ 1.2569524]], B: [0.]
y_tf :[[11.36009]]
y_man :[[11.36009]]
===== 1 =====
x :[[10. 20.]]
init :[]
W: [[1.3344394 ]
 [0.81205165]], B: [0.]
y_tf :[[29.585426]]
y_man :[[29.585426]]
===== 2 =====


# parameter initializer

In [25]:
from tensorflow.keras.initializers import Constant # 원하는값으로 초기값 셋팅할수있음

In [27]:
w,b = tf.constant(10.), tf.constant(20.)
w_init, b_init = Constant(w), Constant(b)

In [28]:
print(w_init,b_init) # 초기화시켜주는 object, 값이 아님

<keras.initializers.initializers_v2.Constant object at 0x7f34e83ce410> <keras.initializers.initializers_v2.Constant object at 0x7f34e83ce390>


In [41]:
# affine function
x = tf.constant([[10.]])
dense = Dense(units=1,
             activation='linear',
             kernel_initializer=w_init,
             bias_initializer=b_init)
y_tf=dense(x)

W,B=dense.get_weights()

print(x) # x가 row vector, T의 주체가됨.(원래 vector라서 세로) 이유는 보기편해서 그렇게 쓰기시작함..
print(W,B) # 그래서 W는 벡터 그대로 세로로 구성되어있음
# 암튼 넣어준 셋팅이 잘 들어가있는걸 확인할 수 있음

print(y_tf)

tf.Tensor([[10.]], shape=(1, 1), dtype=float32)
[[10.]] [20.]
tf.Tensor([[120.]], shape=(1, 1), dtype=float32)


In [40]:
# affine function
x = tf.constant([[10.,20.]])
dense = Dense(units=1,
             activation='linear',
             kernel_initializer=w_init,
             bias_initializer=b_init)
y_tf=dense(x)

W,B=dense.get_weights()

print(x) 
print(W,B) 
print(y_tf) # 스칼라

tf.Tensor([[10. 20.]], shape=(1, 2), dtype=float32)
[[10.]
 [10.]] [20.]
tf.Tensor([[320.]], shape=(1, 1), dtype=float32)


# with n features

In [43]:
x=tf.random.uniform(shape=(1,10), minval=0, maxval=10)
print(x)

tf.Tensor(
[[1.3972139 6.8853416 5.9009814 7.8735995 7.2339525 6.7133274 6.521467
  7.089095  4.6512675 9.065267 ]], shape=(1, 10), dtype=float32)


In [52]:
dense= Dense(units=1)
y_tf=dense(x) # 여기서 w,b초기화됨
W,B = dense.get_weights()
y_man=tf.linalg.matmul(x,W)+B
    
print(x) 
print(W,B) 
print(y_tf) 
print(y_man) 

tf.Tensor(
[[1.3972139 6.8853416 5.9009814 7.8735995 7.2339525 6.7133274 6.521467
  7.089095  4.6512675 9.065267 ]], shape=(1, 10), dtype=float32)
[[ 0.5331724 ]
 [ 0.33689493]
 [ 0.62697357]
 [ 0.7281448 ]
 [-0.294192  ]
 [ 0.07094663]
 [ 0.32891804]
 [ 0.5812668 ]
 [-0.65473163]
 [ 0.30671114]] [0.]
tf.Tensor([[16.846361]], shape=(1, 1), dtype=float32)
tf.Tensor([[16.846361]], shape=(1, 1), dtype=float32)


# activation function

In [59]:
from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation

In [79]:
for iii in range(2):
    print(f'===== {iii} =====')
    x=tf.random.normal(shape=(1,5))

    sigmoid=Activation('sigmoid')
    tanh=Activation('tanh')
    relu=Activation('relu')

    y_sigmoid_tf=sigmoid(x)
    y_tanh_tf=tanh(x)
    y_relu_tf=relu(x)

    y_sigmoid_man= 1 / (1+exp(-x))
    y_tanh_man= (exp(x)-exp(-x))/ (exp(x)+exp(-x))
    y_relu_man= maximum(x,0)

    print(f'x: {x.numpy()}')
    print('sigmoid')
    print(y_sigmoid_tf.numpy())
    print(y_sigmoid_man.numpy())

    print('tanh')
    print(y_tanh_tf.numpy())
    print(y_tanh_man.numpy())

    print('relu')
    print(y_relu_tf.numpy())
    print(y_relu_man.numpy())

===== 0 =====
x: [[-0.1335118 -0.675061   1.388644   1.4651606  0.9662373]]
sigmoid
[[0.46667156 0.33736452 0.80037564 0.8123207  0.7243689 ]]
[[0.46667156 0.33736452 0.8003757  0.8123207  0.7243689 ]]
tanh
[[-0.13272409 -0.58829916  0.8828722   0.8986503   0.7470462 ]]
[[-0.13272412 -0.5882992   0.88287216  0.8986502   0.74704623]]
relu
[[0.        0.        1.388644  1.4651606 0.9662373]]
[[0.        0.        1.388644  1.4651606 0.9662373]]
===== 1 =====
x: [[-0.9960115   0.37351587 -0.89543474 -0.5528513  -1.2225705 ]]
sigmoid
[[0.2697263  0.5923083  0.28998956 0.3652031  0.2274844 ]]
[[0.26972634 0.5923082  0.28998956 0.36520314 0.22748442]]
tanh
[[-0.75991404  0.3570632  -0.71406776 -0.50265414 -0.8404108 ]]
[[-0.759914    0.35706314 -0.71406764 -0.50265414 -0.8404108 ]]
relu
[[0.         0.37351587 0.         0.         0.        ]]
[[0.         0.37351587 0.         0.         0.        ]]


![그래프으](https://mblogthumb-phinf.pstatic.net/MjAyMDAyMjVfMTQ3/MDAxNTgyNjA5NDY3MTY3.228bUv_5mrol1w7X0NiFMD1UNru9zyf3yIJGcON-An0g.3Kzynlja9y_F9yTfANl937elQAK1pTGoJ_al7Om7TYsg.PNG.handuelly/image.png?type=w800)

In [101]:
x=tf.random.normal(shape=(1,5))
dense_sigmoid=Dense(units=1, activation='sigmoid',
                    kernel_initializer=w_init,
                     bias_initializer=b_init)
dense_tanh=Dense(units=1, activation='tanh',
                    kernel_initializer=w_init,
                     bias_initializer=b_init)
dense_relu=Dense(units=1, activation='relu',
                    kernel_initializer=w_init,
                     bias_initializer=b_init)
print(dense_sigmoid.get_weights())
print(dense_tanh.get_weights())
print(dense_relu.get_weights())

y_sigmoid=dense_sigmoid(x)
y_tanh=dense_tanh(x)
y_relu=dense_relu(x)

print(dense_sigmoid.get_weights())
print(dense_tanh.get_weights())
print(dense_relu.get_weights())

# 스칼라 만들때까지 W,B 당연히 동일

[]
[]
[]
[array([[10.],
       [10.],
       [10.],
       [10.],
       [10.]], dtype=float32), array([20.], dtype=float32)]
[array([[10.],
       [10.],
       [10.],
       [10.],
       [10.]], dtype=float32), array([20.], dtype=float32)]
[array([[10.],
       [10.],
       [10.],
       [10.],
       [10.]], dtype=float32), array([20.], dtype=float32)]


In [95]:
for ii in range(3):
    print('======')
    x=tf.random.normal(shape=(1,5))
    dense_sigmoid=Dense(units=1, activation='sigmoid')
    dense_tanh=Dense(units=1, activation='tanh')
    dense_relu=Dense(units=1, activation='relu')

    # forward propagation
    y_sigmoid=dense_sigmoid(x)
    y_tanh=dense_tanh(x)
    y_relu=dense_relu(x)

    print(f'y_sigmoid :{y_sigmoid.numpy()}') # W,B타고나온 스칼라값에 태우는것이기 때문에 스칼라임
    print(f'y_tanh :{y_tanh.numpy()}')
    print(f'y_relu :{y_relu.numpy()}')
    # 크기는 제각각이긴 하네
    
    w,b = dense_sigmoid.get_weights()
    z= tf.linalg.matmul(x,w)+b
    a = 1/(1+exp(-z))
    
    print(f'y_sigmoid :{y_sigmoid.numpy()}')
    print(f'a :{a.numpy()}')

y_sigmoid :[[0.57127315]]
y_tanh :[[0.8933138]]
y_relu :[[0.27782315]]
y_sigmoid :[[0.57127315]]
a :[[0.57127315]]
y_sigmoid :[[0.6230923]]
y_tanh :[[-0.9600379]]
y_relu :[[0.]]
y_sigmoid :[[0.6230923]]
a :[[0.6230923]]
y_sigmoid :[[0.19291122]]
y_tanh :[[-0.22478244]]
y_relu :[[1.3350224]]
y_sigmoid :[[0.19291122]]
a :[[0.19291122]]


# minibatches

In [107]:
# 미니배치 사이즈는 W,B에 영향을 미치지 않음
N, n_features = 8000,10 
x = tf.random.normal(shape=(N, n_features))
print(x.shape) # row vector

dense = Dense(units=1, activation='relu')
y=dense(x)

W,B = dense.get_weights()
print(W,B) ##### <- 사실상 이거 형태 생긴거 보려고 지금까지 한거임..
print(x.shape, W.shape, B.shape)

(8000, 10)
[[ 0.06125021]
 [-0.1204198 ]
 [-0.18354303]
 [ 0.47030133]
 [-0.4995182 ]
 [-0.15719211]
 [ 0.34705073]
 [ 0.03163803]
 [ 0.09772104]
 [-0.0639376 ]] [0.]
(8000, 10) (10, 1) (1,)


In [114]:
N, n_features = 8,10 
x = tf.random.normal(shape=(N, n_features))
dense = Dense(units=1, activation='sigmoid')
y_tf=dense(x)

W, B =dense.get_weights()

y_man = tf.linalg.matmul(x,W)+B
y_man = 1/ (1+exp(-y_man))

print(f'y_tf: \n {y_tf.numpy()}')
print(f'y_man: \n{y_man.numpy()}')

y_tf: 
 [[0.35593018]
 [0.8355185 ]
 [0.8939175 ]
 [0.53791136]
 [0.888183  ]
 [0.05093066]
 [0.8572016 ]
 [0.9290523 ]]
y_man: 
[[0.35593018]
 [0.8355185 ]
 [0.89391756]
 [0.5379114 ]
 [0.88818294]
 [0.05093066]
 [0.8572016 ]
 [0.9290523 ]]
