# dense layer

In [ ]:
딥러닝 architecture
corelation filter들을 묶어서 filter bank를 만들고
그 filter bank의 Cascaded 구조가 딥러닝 구조임

블랙박스가 아니다
MFCC가 여기서 나오네.. 

In [ ]:
뉴런마다 인풋값이 전부다 연결되어있는것
네트워크
node(뉴런)-edge(커넥션)

In [ ]:
선형대수특 값을 따로 가지고다니기 귀찮아서 한꺼번에 vector, matrix 형태로 가지고다님
셋팅한 1,2,3...n개의 뉴런의 연산을 그대로 해줄 수 있는 구조로 만든거임

$$x^TW+b^T$$

In [ ]:
bias로 row vector로 만드는데, 나중에 broadcasting같은 기능 사용할때 더 편함

In [ ]:
그리고 그냥 뉴런 하나씩 연산하고 activation scalar형태로 태우는거니까
뉴런갯수만큼 vector가 layer의 output으로 나오겠지
뉴련갯수 왜 헷갈리게 l로 표기하는걸까..

$$R^{1 \times l}$$

In [ ]:
row vector(xT)를 넣어서 row vertor(결국 각각의 activation value들)가 나온다

In [ ]:
저번시간이랑 다른게 뭔지 잘 모르겠네

# generalize

In [ ]:
그 다음 레이어부터는 xT가 아니라 output자체가 넘어옴. l길이를 가진 row vector
새로운 xT로 봐줘도 되겠다.

$$W \in {R^{l_{i-1} \times l_i}}$$

In [ ]:
결국 이전 결과 i-1번째의 뉴런길이 l_{i-1}와 현재 뉴런길이가 W의 크기를 만듦

# minibatches
이제 영민이에서.. 민수, 민지가 생김

$$R^{1\times l}$$ 을 쓴게..
&rightarrow;
$$R^{N\times l}$$ 할려고였군..

In [ ]:
matrix가 있을때 가로(row)는 각각 사람(N)에 대한거고 (Batch-wise)
열은 셋팅한 과목수 or 모든 과목의 정보를 담고있는 뉴런수임 (Neuron-wise)

하나의 mini batch는 하나의반임

구니까 원래 구조를 떠올리려면 한사람만 떠올리면 됨

# Dense Laysers

## shape

In [7]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature =1, 10
X= tf.random.normal(shape=(N,n_feature))

n_neuron=3
dense=Dense(units=n_neuron, activation='sigmoid')
Y=dense(X)

W,B = dense.get_weights()

print('X:',X.shape)
print('W:',W.shape)
print('B:',B.shape)
print('Y:',Y.shape)
print()
print(W)
print()
print(Y)

X: (1, 10)
W: (10, 3)
B: (3,)
Y: (1, 3)

[[-0.41952312  0.4716655  -0.5002242 ]
 [ 0.5600183   0.5002588   0.10658395]
 [ 0.4985876  -0.27985284  0.27077603]
 [-0.10455358 -0.592419   -0.01186359]
 [-0.01741588  0.37600327  0.3161683 ]
 [-0.23857275 -0.56369627  0.39198697]
 [ 0.45858657  0.3405639  -0.21674198]
 [-0.03214979  0.5238031  -0.6376017 ]
 [-0.05144036  0.50637543  0.453781  ]
 [ 0.43707895 -0.07747614 -0.16472238]]

tf.Tensor([[0.6508973 0.4733562 0.6782346]], shape=(1, 3), dtype=float32)


In [13]:
import tensorflow as tf
import numpy as np

from tensorflow.math import exp
from tensorflow.linalg import matmul

from tensorflow.keras.layers import Dense

N, n_feature =5, 10
X= tf.random.normal(shape=(N,n_feature))

n_neuron=3
dense=Dense(units=n_neuron, activation='sigmoid')
Y=dense(X)

W,B = dense.get_weights()

print('X:',X.shape)
print('W:',W.shape)
print('B:',B.shape)
print('Y:',Y.shape)
print()
print(W)
print()
print('Y(tensor):',Y)

# calculate with matrix multiplication
z=matmul(X,W)+B
y_man_matmul=1/(1+exp(-z))
print('Y(man_matmul):',y_man_matmul)

# numpy로 (tensor은 역전파때매 슬라이싱 입력 불가하기 때매 numpy로)
y_man_vec=np.zeros(shape=(N,n_neuron))
for x_idx in range(N):
    x=X[x_idx]
    for nu_idx in range(n_neuron):
        w, b=W[:, nu_idx], B[nu_idx]
        # 이게 dot product인가 보네?
        z=tf.reduce_sum(x*w)+b
        a=1/(1+np.exp(-z))
        y_man_vec[x_idx, nu_idx]=a
        
print('Y(y_man_vec):',y_man_vec)


X: (5, 10)
W: (10, 3)
B: (3,)
Y: (5, 3)

[[-0.66481113 -0.52674556 -0.61355346]
 [ 0.40042913  0.34762692 -0.35688666]
 [ 0.411991   -0.39023295 -0.20915076]
 [ 0.4533671   0.21780533 -0.12565094]
 [-0.15490568 -0.40375385  0.04237068]
 [ 0.09114134 -0.31263256 -0.4698606 ]
 [ 0.04551554 -0.22495773 -0.2946378 ]
 [-0.17980325  0.3099935   0.11367899]
 [ 0.19926697  0.6702039   0.3964895 ]
 [ 0.2754177  -0.214158   -0.65305364]]

Y(tensor): tf.Tensor(
[[0.427451   0.74169433 0.807637  ]
 [0.44275445 0.09695899 0.07993889]
 [0.4634342  0.4604019  0.52215827]
 [0.51897854 0.7522563  0.81984365]
 [0.44413015 0.4013339  0.28929877]], shape=(5, 3), dtype=float32)
Y(man_matmul): tf.Tensor(
[[0.427451   0.74169433 0.807637  ]
 [0.44275445 0.09695899 0.07993888]
 [0.46343422 0.46040192 0.5221583 ]
 [0.51897854 0.75225633 0.8198437 ]
 [0.44413015 0.40133393 0.2892988 ]], shape=(5, 3), dtype=float32)
Y(y_man_vec): [[0.42745101 0.74169434 0.80763698]
 [0.44275439 0.09695896 0.07993889]
 [0.4634342

# cascaded dense layer

In [39]:
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.linalg import matmul

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X= tf.random.normal(shape=(N, n_feature))
X_cp = tf.identity(X) # 데이터 좌표값 다르게 카피하기 위함

n_neurons = [100,20,30]

dense_layers = list()

for n_neuron in n_neurons:
    dense = Dense(units=n_neuron, activation='relu')
    dense_layers.append(dense)

print('input X.shape',X.shape)

for dense_idx, dense in enumerate(dense_layers):
    X = dense(X)
    print('next dense idx',dense_idx+1)
    print(X.shape,'\n')

input X.shape (4, 10)
next dense idx 1
(4, 100) 

next dense idx 2
(4, 20) 

next dense idx 3
(4, 30) 



In [54]:
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.linalg import matmul

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X= tf.random.normal(shape=(N, n_feature))
print('init X.shape',X.shape)
X_cp = tf.identity(X) # 데이터 주소값 다르게 카피하기 위함

n_neurons = [3,4,5]

dense_layers = list()
for n_neuron in n_neurons:
    dense = Dense(units=n_neuron, activation='sigmoid')
    dense_layers.append(dense)
    
# forward propagation (tensorflow)
W, B = list(), list()
for dense_idx, dense in enumerate(dense_layers):
    X = dense(X)
    w, b = dense.get_weights() ##### 사실상 여기만들기위해서 함수를만든것
    
    W.append(w)
    B.append(b)
print('tensorflow result :\n',X) # 4개의 minibatch, 5개의 output

# forward propagation (manual)
for layer_idx in range(len(n_neurons)):
    w,b = W[layer_idx], B[layer_idx]
    
    X_cp = matmul(X_cp,w) + b
    X_cp = 1/(1+ exp(-X_cp))
    
print('manual result :\n',X_cp)

init X.shape (4, 10)
tensorflow result :
 tf.Tensor(
[[0.5770336  0.6517063  0.4497505  0.3754923  0.37081444]
 [0.5785256  0.65142393 0.46340042 0.37827572 0.37299103]
 [0.5821927  0.6452699  0.4535228  0.365272   0.37594804]
 [0.57575893 0.6400241  0.40802988 0.36742997 0.37761903]], shape=(4, 5), dtype=float32)
manual result :
 tf.Tensor(
[[0.57703364 0.6517063  0.44975057 0.37549227 0.37081444]
 [0.57852554 0.6514239  0.46340042 0.37827566 0.37299103]
 [0.5821927  0.6452699  0.4535228  0.36527196 0.375948  ]
 [0.575759   0.6400241  0.40802985 0.36742994 0.377619  ]], shape=(4, 5), dtype=float32)


# model implementation -Sequential

In [58]:
from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Sequential

# n_neurons=[3,4,5,6]

# model=list()
# for n_neuron in n_neurons:
#     model.append(Dense(units=n_neuron, activation='sigmoid'))
    
# model=Sequential()
# for n_neuron in n_neurons:
#     model.add(Dense(units=n_neuron, activation='sigmoid'))
    
    
model = Sequential() # Sequential : 모든 레이어가 연속적으로 이어져있음 (반례 residual같은 구조)
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=20, activation='sigmoid'))

# model implementation with Model-subclassing

In [62]:
from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Model

# 설계만
class TestModel(Model):
    def __init__(self):
        super(TestModel, self).__init__()
        
        self.dense1 = Dense(units=10, activation='sigmoid')
        self.dense2 = Dense(units=20, activation='sigmoid')
        
model=TestModel()

# forward propagation by method

In [66]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

from tensorflow.keras.models import Sequential
from tensorflow.keras.models import Model

X= tf.random.normal(shape=(4,10))

# Sequential
model = Sequential() # Sequential : 모든 레이어가 연속적으로 이어져있음 (반례 residual같은 구조)
model.add(Dense(units=2, activation='sigmoid'))
model.add(Dense(units=3, activation='sigmoid'))
Y=model(X)
print('Sequential \n',Y.numpy())

# Model-subclassing
class TestModel(Model):
    def __init__(self):
        super(TestModel, self).__init__()
        
        self.dense1 = Dense(units=2, activation='sigmoid')
        self.dense2 = Dense(units=3, activation='sigmoid')
        
    def call(self,x): # Sequential 구조뿐 아니라 다른구조의 layer도 같이 구성가능해짐
        x= self.dense1(x)
        x= self.dense2(x)
        return x      
model = TestModel()
Y=model(X)
print('Model-subclassing \n',Y.numpy())

Sequential 
 [[0.52097195 0.51046455 0.49297002]
 [0.5257906  0.5138255  0.49162364]
 [0.5015352  0.51093894 0.5023775 ]
 [0.48264214 0.5100943  0.5111468 ]]
Model-subclassing 
 [[0.52940357 0.46731427 0.67074335]
 [0.5904248  0.4594844  0.6780982 ]
 [0.5350664  0.4814275  0.58850074]
 [0.6183733  0.44682696 0.7267448 ]]


In [61]:
class TestModel(Model):
    def __init__(self, n_neurons):
        super(TestModel, self).__init__()
        self.n_neurons = n_neurons
        self.dense_layers = list()
        
        for n_neuron in n_neurons:
            self.dense_layers.append(Dense(units=n_neuron, activation='sigmoid'))
        
    def call(self,x): # Sequential 구조뿐 아니라 다른구조의 layer도 같이 구성가능해짐
        for dense in self.dense_layers:
            x=dense(x)
        return x

class TestModel(Model):
    def __init__(self, n_neurons):
        super(TestModel, self).__init__()
        self.n_neurons = n_neurons
        self.model = Sequential() # Sequential : 모든 레이어가 연속적으로 이어져있음 (반례 residual같은 구조)
        self.model.add(Dense(units=10, activation='sigmoid'))
        self.model.add(Dense(units=20, activation='sigmoid'))

    def call(self,x): # Sequential 구조뿐 아니라 다른구조의 layer도 같이 구성가능해짐
        x=self.model(x)
        return x
    
n_neurons = [3,4,5]
model=TestModel(n_neurons)

# layers in models

In [71]:
X= tf.random.normal(shape=(4,10))

# Sequential
model = Sequential() # Sequential : 모든 레이어가 연속적으로 이어져있음 (반례 residual같은 구조)
model.add(Dense(units=2, activation='sigmoid'))
model.add(Dense(units=3, activation='sigmoid'))
Y=model(X)

print(type(model.layers))
print(model.layers)

<class 'list'>
[<keras.layers.core.dense.Dense object at 0x7f8d50206cd0>, <keras.layers.core.dense.Dense object at 0x7f8bc0631e90>]


In [72]:
for layer in model.layers:
    w,b = layer.get_weights()
    print(w.shape, b.shape)

(10, 2) (2,)
(2, 3) (3,)


In [69]:
dense1 = model.layers[0]

In [78]:
print(dir(dense1))

['_TF_MODULE_IGNORED_PROPERTIES', '__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_activity_regularizer', '_add_trackable', '_add_trackable_child', '_add_variable_with_custom_getter', '_auto_config', '_auto_get_config', '_auto_track_sub_layers', '_autocast', '_autographed_call', '_build_input_shape', '_call_spec', '_callable_losses', '_captured_weight_regularizer', '_cast_single_input', '_checkpoint_dependencies', '_clear_losses', '_compute_dtype', '_compute_dtype_object', '_dedup_weights', '_deferred_dependencies', '_delete_tracking', '_deserialization_dependencies', '_deserialize_from_proto', '_dtype', '_dtype_policy', '_dynamic', '_eager_losses', '

# trainable_variables in models

In [76]:
X= tf.random.normal(shape=(4,10))

# Sequential
model = Sequential() # Sequential : 모든 레이어가 연속적으로 이어져있음 (반례 residual같은 구조)
model.add(Dense(units=2, activation='sigmoid'))
model.add(Dense(units=3, activation='sigmoid'))
Y=model(X)

print(type(model.trainable_variables))
print(len(model.trainable_variables))

for temp in model.trainable_variables: # 학습 대상이되는 variable들이 들어있음
    print(type(temp))
    print(temp.shape)
    print(temp)

<class 'list'>
4
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
(10, 2)
<tf.Variable 'dense_106/kernel:0' shape=(10, 2) dtype=float32, numpy=
array([[ 0.25764197, -0.06895328],
       [ 0.29453248, -0.33223855],
       [-0.6127316 , -0.07995242],
       [ 0.7023575 ,  0.6406508 ],
       [-0.4453826 ,  0.65480083],
       [-0.32135606,  0.6879274 ],
       [ 0.5607249 ,  0.22435713],
       [ 0.03787065,  0.14771187],
       [-0.43753013, -0.57617706],
       [-0.43138292, -0.46534958]], dtype=float32)>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
(2,)
<tf.Variable 'dense_106/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
(2, 3)
<tf.Variable 'dense_107/kernel:0' shape=(2, 3) dtype=float32, numpy=
array([[ 0.9667678 ,  0.7102977 , -0.66608554],
       [ 0.44596505,  0.51039946,  0.89250946]], dtype=float32)>
<class 'tensorflow.python.ops.resou